# Scrapy settings for FoodsSpider project
#
# For simplicity, this file contains only settings considered important or
# commonly used. You can find more settings consulting the documentation:
#
#     https://docs.scrapy.org/en/latest/topics/settings.html
#     https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
#     https://docs.scrapy.org/en/latest/topics/spider-middleware.html

BOT_NAME = "FoodsSpider"

SPIDER_MODULES = ["FoodsSpider.spiders"]
NEWSPIDER_MODULE = "FoodsSpider.spiders"
MYSQL_CONNECT = {
    'host': '10.8.16.253',
    'port': 3306,
    'user': 'root',
    'password': 'fiang123',
    'charset': 'utf8',
    'db': 'spider'
}

LOG_LEVEL = 'INFO'
COOKIES_ENABLED = False
# Obey robots.txt rules
ROBOTSTXT_OBEY = False

TYPES=[('https://www.xiangha.com/caipu/s-zhurou/', '猪肉'),
 ('https://www.xiangha.com/caipu/s-paigu/', '排骨'),
 ('https://www.xiangha.com/caipu/s-zhuti/', '猪蹄'),
 ('https://www.xiangha.com/caipu/s-zhudu/', '猪肚'),
 ('https://www.xiangha.com/caipu/s-wuhuarou/', '五花肉'),
 ('https://www.xiangha.com/caipu/s-zhugan/', '猪肝'),
 ('https://www.xiangha.com/caipu/s-zhuxue/', '猪血'),
 ('https://www.xiangha.com/caipu/s-zhuyao/', '猪腰'),
 ('https://www.xiangha.com/caipu/s-zhupi/', '猪皮'),
 ('https://www.xiangha.com/caipu/s-zhuzhou/', '猪肘'),
 ('https://www.xiangha.com/caipu/s-zhuerduo/', '猪耳朵'),
 ('https://www.xiangha.com/caipu/s-zhuxin/', '猪心'),
 ('https://www.xiangha.com/caipu/s-zhufei/', '猪肺'),
 ('https://www.xiangha.com/caipu/s-zhudachang/', '猪大肠'),
 ('https://www.xiangha.com/caipu/s-zhudagutou/', '猪大骨头'),
 ('https://www.xiangha.com/caipu/s-zhuxiaopai/', '猪小排'),
 ('https://www.xiangha.com/caipu/s-zhulijirou/', '猪里脊肉'),
 ('https://www.xiangha.com/caipu/s-zhupai/', '猪排'),
 ('https://www.xiangha.com/caipu/s-zhushetou/', '猪舌头'),

 ('https://www.xiangha.com/caipu/s-niurou/', '牛肉'),
 ('https://www.xiangha.com/caipu/s-niunan/', '牛腩'),
 ('https://www.xiangha.com/caipu/s-niupai/', '牛排'),
 ('https://www.xiangha.com/caipu/s-feiniu/', '肥牛'),
 ('https://www.xiangha.com/caipu/s-niudu/', '牛肚'),
 ('https://www.xiangha.com/caipu/s-niutijin/', '牛蹄筋'),
 ('https://www.xiangha.com/caipu/s-niuwei/', '牛尾'),

 ('https://www.xiangha.com/caipu/s-yangrou/', '羊肉'),
 ('https://www.xiangha.com/caipu/s-yangpai/', '羊排'),
 ('https://www.xiangha.com/caipu/s-yanggan/', '羊肝'),
 ('https://www.xiangha.com/caipu/s-yangxiezi/', '羊蝎子'),
 ('https://www.xiangha.com/caipu/s-yanggu/', '羊骨'),

 ('https://www.xiangha.com/caipu/s-jirou/', '鸡肉'),
 ('https://www.xiangha.com/caipu/s-jichi/', '鸡翅'),
 ('https://www.xiangha.com/caipu/s-jitui/', '鸡腿'),
 ('https://www.xiangha.com/caipu/s-jizhao/', '鸡爪'),
 ('https://www.xiangha.com/caipu/s-jigan/', '鸡肝'),
 ('https://www.xiangha.com/caipu/s-jizhen/', '鸡胗'),
 ('https://www.xiangha.com/caipu/s-jixin/', '鸡心'),
 ('https://www.xiangha.com/caipu/s-huojirou/', '火鸡肉'),
 ('https://www.xiangha.com/caipu/s-wugujirou/', '乌鸡'),

 ('https://www.xiangha.com/caipu/s-yarou/', '鸭肉'),
 ('https://www.xiangha.com/caipu/s-yagan/', '鸭肝'),
 ('https://www.xiangha.com/caipu/s-yatui/', '鸭腿'),
 ('https://www.xiangha.com/caipu/s-yachi/', '鸭翅'),
 ('https://www.xiangha.com/caipu/s-yazhen/', '鸭胗'),
 ('https://www.xiangha.com/caipu/s-yaxue/', '鸭血'),
 ('https://www.xiangha.com/caipu/s-yazhang/', '鸭掌'),
 ('https://www.xiangha.com/caipu/s-yachang/', '鸭肠'),

 ('https://www.xiangha.com/caipu/s-larou/', '腊肉'),
 ('https://www.xiangha.com/caipu/s-huotui/', '火腿'),
 ('https://www.xiangha.com/caipu/s-xiangchang/', '香肠'),
 ('https://www.xiangha.com/caipu/s-xianrou/', '咸肉'),
 ('https://www.xiangha.com/caipu/s-rousong/', '肉松'),
 ('https://www.xiangha.com/caipu/s-peigen/', '培根'),
 ('https://www.xiangha.com/caipu/s-wucanrou/', '午餐肉'),
 ('https://www.xiangha.com/caipu/s-xunrou/', '熏肉'),

 ('https://www.xiangha.com/caipu/s-turou/', '兔肉'),
 ('https://www.xiangha.com/caipu/s-lurou1/', '鹿肉'),
 ('https://www.xiangha.com/caipu/s-lvrou/', '驴肉'),
 ('https://www.xiangha.com/caipu/s-xueha/', '雪蛤'),
 ('https://www.xiangha.com/caipu/s-canyong/', '蚕蛹'),
 ('https://www.xiangha.com/caipu/s-egan/', '鹅肝'),
 ('https://www.xiangha.com/caipu/s-ruge/', '乳鸽'),
 ('https://www.xiangha.com/caipu/s-gerou/', '鸽肉'),

 ('https://www.xiangha.com/caipu/s-jidan/', '鸡蛋'),
 ('https://www.xiangha.com/caipu/s-yadan/', '鸭蛋'),
 ('https://www.xiangha.com/caipu/s-anchundan/', '鹌鹑蛋'),
 ('https://www.xiangha.com/caipu/s-xianyadan/', '咸鸭蛋'),
 ('https://www.xiangha.com/caipu/s-songhuadan/', '松花蛋'),

 ('https://www.xiangha.com/caipu/s-nailao/', '奶酪'),
 ('https://www.xiangha.com/caipu/s-huangyou/', '黄油'),
 ('https://www.xiangha.com/caipu/s-naiyou/', '奶油'),

 ('https://www.xiangha.com/caipu/s-caoyu/', '草鱼'),
 ('https://www.xiangha.com/caipu/s-liyu/', '鲤鱼'),
 ('https://www.xiangha.com/caipu/s-jiyu/', '鲫鱼'),
 ('https://www.xiangha.com/caipu/s-lianyu/', '鲢鱼'),
 ('https://www.xiangha.com/caipu/s-qingyu/', '青鱼'),
 ('https://www.xiangha.com/caipu/s-nianyu/', '鲶鱼'),
 ('https://www.xiangha.com/caipu/s-yinyu/', '银鱼'),
 ('https://www.xiangha.com/caipu/s-luofeiyu/', '罗非鱼'),
 ('https://www.xiangha.com/caipu/s-wuchangyu/', '武昌鱼'),
 ('https://www.xiangha.com/caipu/s-bianyu/', '鳊鱼'),
 ('https://www.xiangha.com/caipu/s-guiyu/', '桂鱼'),
 ('https://www.xiangha.com/caipu/s-wuli/', '乌鳢'),
 ('https://www.xiangha.com/caipu/s-niqiu/', '泥鳅'),
 ('https://www.xiangha.com/caipu/s-huangshan/', '黄鳝'),

 ('https://www.xiangha.com/caipu/s-daiyu/', '带鱼'),
 ('https://www.xiangha.com/caipu/s-luyu/', '鲈鱼'),
 ('https://www.xiangha.com/caipu/s-xueyu/', '鳕鱼'),
 ('https://www.xiangha.com/caipu/s-bayu/', '鲅鱼'),
 ('https://www.xiangha.com/caipu/s-jinqiangyu/', '金枪鱼'),
 ('https://www.xiangha.com/caipu/s-changyu/', '鲳鱼'),
 ('https://www.xiangha.com/caipu/s-manyu/', '鳗鱼'),
 ('https://www.xiangha.com/caipu/s-sanwenyu/', '三文鱼'),
 ('https://www.xiangha.com/caipu/s-longliyu/', '龙利鱼'),
 ('https://www.xiangha.com/caipu/s-suoyu/', '梭鱼'),
 ('https://www.xiangha.com/caipu/s-qiudaoyu/', '秋刀鱼'),
 ('https://www.xiangha.com/caipu/s-bimuyu/', '比目鱼'),
 ('https://www.xiangha.com/caipu/s-shadingyu/', '沙丁鱼'),
 ('https://www.xiangha.com/caipu/s-duochunyu/', '多春鱼'),
 ('https://www.xiangha.com/caipu/s-shibanyu/', '石斑鱼'),
 ('https://www.xiangha.com/caipu/s-diaoyu/', '鲷鱼'),
 ('https://www.xiangha.com/caipu/s-laobanyu/', '老板鱼'),
 ('https://www.xiangha.com/caipu/s-huanghuayu/', '黄花鱼'),
 ('https://www.xiangha.com/caipu/s-mamianyu/', '马面鱼'),
 ('https://www.xiangha.com/caipu/s-xiaohuangyu/', '小黄鱼'),

 ('https://www.xiangha.com/caipu/s-yuwan/', '鱼丸'),
 ('https://www.xiangha.com/caipu/s-yutou1/', '鱼头'),
 ('https://www.xiangha.com/caipu/s-yugan/', '鱼干'),
 ('https://www.xiangha.com/caipu/s-yuzi/', '鱼籽'),
 ('https://www.xiangha.com/caipu/s-huajiao1/', '花胶'),

 ('https://www.xiangha.com/caipu/s-xia/', '虾'),
 ('https://www.xiangha.com/caipu/s-xiami/', '虾米'),
 ('https://www.xiangha.com/caipu/s-longxia/', '龙虾'),
 ('https://www.xiangha.com/caipu/s-xiapi/', '虾皮'),
 ('https://www.xiangha.com/caipu/s-haixia/', '海虾'),
 ('https://www.xiangha.com/caipu/s-beijixia/', '北极虾'),
 ('https://www.xiangha.com/caipu/s-jiweixia/', '基围虾'),
 ('https://www.xiangha.com/caipu/s-xiaolongxia/', '小龙虾'),
 ('https://www.xiangha.com/caipu/s-hexia/', '河虾'),
 ('https://www.xiangha.com/caipu/s-pipixia/', '皮皮虾'),
 ('https://www.xiangha.com/caipu/s-xiaren/', '虾仁'),

 ('https://www.xiangha.com/caipu/s-bangxie/', '螃蟹'),
 ('https://www.xiangha.com/caipu/s-suozixie/', '梭子蟹'),
 ('https://www.xiangha.com/caipu/s-hexie/', '河蟹'),

 ('https://www.xiangha.com/caipu/s-hali/', '蛤蜊'),
 ('https://www.xiangha.com/caipu/s-muli/', '牡蛎'),
 ('https://www.xiangha.com/caipu/s-baoyu/', '鲍鱼'),
 ('https://www.xiangha.com/caipu/s-ganbei/', '干贝'),
 ('https://www.xiangha.com/caipu/s-shanbei/', '扇贝'),
 ('https://www.xiangha.com/caipu/s-xianbei/', '鲜贝'),
 ('https://www.xiangha.com/caipu/s-wenha/', '文蛤'),
 ('https://www.xiangha.com/caipu/s-chengzi1/', '蛏子'),
 ('https://www.xiangha.com/caipu/s-hailuo/', '海螺'),
 ('https://www.xiangha.com/caipu/s-qingkou/', '青口'),
 ('https://www.xiangha.com/caipu/s-hebang/', '河蚌'),
 ('https://www.xiangha.com/caipu/s-dancai/', '淡菜'),
 ('https://www.xiangha.com/caipu/s-shengci/', '生蚝'),
 ('https://www.xiangha.com/caipu/s-beijibei/', '北极贝'),

 ('https://www.xiangha.com/caipu/s-haidai/', '海带'),
 ('https://www.xiangha.com/caipu/s-zicai/', '紫菜'),
 ('https://www.xiangha.com/caipu/s-qundaicai/', '裙带菜'),
 ('https://www.xiangha.com/caipu/s-haizao/', '海藻'),
 ('https://www.xiangha.com/caipu/s-facai/', '发菜'),

 ('https://www.xiangha.com/caipu/s-moyu/', '墨鱼'),
 ('https://www.xiangha.com/caipu/s-youyu/', '鱿鱼'),
 ('https://www.xiangha.com/caipu/s-zhangyu/', '章鱼'),
 ('https://www.xiangha.com/caipu/s-haishen/', '海参'),
 ('https://www.xiangha.com/caipu/s-jiayu/', '甲鱼'),
 ('https://www.xiangha.com/caipu/s-tianluo/', '田螺'),
 ('https://www.xiangha.com/caipu/s-haizhetou/', '海蜇头'),
 ('https://www.xiangha.com/caipu/s-haizhepi/', '海蜇皮'),
 ('https://www.xiangha.com/caipu/s-tianji/', '田鸡'),
 ('https://www.xiangha.com/caipu/s-niuwa/', '牛蛙'),

 ('https://www.xiangha.com/caipu/s-baicai/', '白菜'),
 ('https://www.xiangha.com/caipu/s-youcai/', '油菜'),
 ('https://www.xiangha.com/caipu/s-qincai/', '芹菜'),
 ('https://www.xiangha.com/caipu/s-bocai/', '菠菜'),
 ('https://www.xiangha.com/caipu/s-xiaobaicai/', '小白菜'),
 ('https://www.xiangha.com/caipu/s-jiucai/', '韭菜'),
 ('https://www.xiangha.com/caipu/s-shengcai/', '生菜'),
 ('https://www.xiangha.com/caipu/s-tonggao/', '茼蒿'),
 ('https://www.xiangha.com/caipu/s-xiangcai/', '香菜'),
 ('https://www.xiangha.com/caipu/s-lusun/', '芦笋'),
 ('https://www.xiangha.com/caipu/s-wancai/', '苋菜'),
 ('https://www.xiangha.com/caipu/s-jiecai/', '芥菜'),
 ('https://www.xiangha.com/caipu/s-wosun/', '莴笋'),
 ('https://www.xiangha.com/caipu/s-jiaobai/', '茭白'),
 ('https://www.xiangha.com/caipu/s-xuelihong/', '雪里蕻'),
 ('https://www.xiangha.com/caipu/s-caihua/', '菜花'),
 ('https://www.xiangha.com/caipu/s-xilanhua/', '西兰花'),
 ('https://www.xiangha.com/caipu/s-huanghuacai/', '黄花菜'),
 ('https://www.xiangha.com/caipu/s-cicai/', '荠菜'),
 ('https://www.xiangha.com/caipu/s-baihe/', '百合'),
 ('https://www.xiangha.com/caipu/s-juecai/', '蕨菜'),
 ('https://www.xiangha.com/caipu/s-ganlancai/', '橄榄菜'),
 ('https://www.xiangha.com/caipu/s-juhua/', '菊花'),
 ('https://www.xiangha.com/caipu/s-wandoujian/', '豌豆尖'),
 ('https://www.xiangha.com/caipu/s-huaihua/', '槐花'),
 ('https://www.xiangha.com/caipu/s-jiuhuang/', '韭黄'),
 ('https://www.xiangha.com/caipu/s-ziganlan/', '紫甘蓝'),
 ('https://www.xiangha.com/caipu/s-xiqin/', '西芹'),
 ('https://www.xiangha.com/caipu/s-huixiang/', '茴香'),
 ('https://www.xiangha.com/caipu/s-wawacai/', '娃娃菜'),
 ('https://www.xiangha.com/caipu/s-jielan/', '芥蓝'),
 ('https://www.xiangha.com/caipu/s-kuju/', '苦菊'),
 ('https://www.xiangha.com/caipu/s-kongxincai/', '空心菜'),
 ('https://www.xiangha.com/caipu/s-youmaicai/', '油麦菜'),
 ('https://www.xiangha.com/caipu/s-malantou/', '马兰头'),
 ('https://www.xiangha.com/caipu/s-shuiqincai/', '水芹菜'),
 ('https://www.xiangha.com/caipu/s-luhui/', '芦荟'),
 ('https://www.xiangha.com/caipu/s-zhimacai/', '芝麻菜'),
 ('https://www.xiangha.com/caipu/s-hongcaitai/', '红菜苔'),
 ('https://www.xiangha.com/caipu/s-juanxincai/', '卷心菜'),
 ('https://www.xiangha.com/caipu/s-suantai/', '蒜薹'),
 ('https://www.xiangha.com/caipu/s-gouqicai/', '枸杞菜'),
 ('https://www.xiangha.com/caipu/s-wandoumiao/', '豌豆苗'),
 ('https://www.xiangha.com/caipu/s-luoboye/', '萝卜叶'),
 ('https://www.xiangha.com/caipu/s-luokui/', '木耳菜'),
 ('https://www.xiangha.com/caipu/s-ligao/', '藜蒿'),
 ('https://www.xiangha.com/caipu/s-machiwan/', '马齿苋'),
 ('https://www.xiangha.com/caipu/s-yuanshengcai/', '圆生菜'),
 ('https://www.xiangha.com/caipu/s-jielan1/', '芥兰'),
 ('https://www.xiangha.com/caipu/s-zibeitiankui/', '紫背天葵'),

 ('https://www.xiangha.com/caipu/s-tudou/', '土豆'),
 ('https://www.xiangha.com/caipu/s-hongshu/', '红薯'),
 ('https://www.xiangha.com/caipu/s-yutou/', '芋头'),
 ('https://www.xiangha.com/caipu/s-huluobo/', '胡萝卜'),
 ('https://www.xiangha.com/caipu/s-bailuobo/', '白萝卜'),
 ('https://www.xiangha.com/caipu/s-zhusun/', '竹笋'),
 ('https://www.xiangha.com/caipu/s-moyu1/', '魔芋'),
 ('https://www.xiangha.com/caipu/s-shanyao/', '山药'),
 ('https://www.xiangha.com/caipu/s-ou/', '藕'),
 ('https://www.xiangha.com/caipu/s-niubang/', '牛蒡'),
 ('https://www.xiangha.com/caipu/s-biqi/', '荸荠'),
 ('https://www.xiangha.com/caipu/s-zishu/', '紫薯'),
 ('https://www.xiangha.com/caipu/s-qingluobo/', '青萝卜'),
 ('https://www.xiangha.com/caipu/s-chunsun/', '春笋'),
 ('https://www.xiangha.com/caipu/s-dongsun/', '冬笋'),
 ('https://www.xiangha.com/caipu/s-lingjiao/', '菱角'),
 ('https://www.xiangha.com/caipu/s-cigu/', '慈菇'),
 ('https://www.xiangha.com/caipu/s-xinlimeiluobo/', '心里美萝卜'),
 ('https://www.xiangha.com/caipu/s-tiancaigen/', '甜菜根'),
 ('https://www.xiangha.com/caipu/s-hongluobo/', '红萝卜'),
 ('https://www.xiangha.com/caipu/s-cigu1/', '慈姑'),
 ('https://www.xiangha.com/caipu/s-qiaotou/', '荞头'),
 ('https://www.xiangha.com/caipu/s-pielan/', '苤蓝'),

 ('https://www.xiangha.com/caipu/s-doujiao/', '豆角'),
 ('https://www.xiangha.com/caipu/s-qiezi/', '茄子'),
 ('https://www.xiangha.com/caipu/s-qingjiao/', '青椒'),
 ('https://www.xiangha.com/caipu/s-xihongshi/', '西红柿'),
 ('https://www.xiangha.com/caipu/s-helandou/', '荷兰豆'),
 ('https://www.xiangha.com/caipu/s-jiangdou/', '豇豆'),
 ('https://www.xiangha.com/caipu/s-biandou/', '扁豆'),
 ('https://www.xiangha.com/caipu/s-huanggua/', '黄瓜'),
 ('https://www.xiangha.com/caipu/s-donggua/', '冬瓜'),
 ('https://www.xiangha.com/caipu/s-kugua/', '苦瓜'),
 ('https://www.xiangha.com/caipu/s-nangua/', '南瓜'),
 ('https://www.xiangha.com/caipu/s-sigua/', '丝瓜'),
 ('https://www.xiangha.com/caipu/s-xihulu/', '西葫芦'),
 ('https://www.xiangha.com/caipu/s-hulu/', '葫芦'),
 ('https://www.xiangha.com/caipu/s-hongjiao/', '红椒'),
 ('https://www.xiangha.com/caipu/s-youdoujiao/', '油豆角'),
 ('https://www.xiangha.com/caipu/s-hugua/', '瓠瓜'),
 ('https://www.xiangha.com/caipu/s-foshougua/', '佛手瓜'),
 ('https://www.xiangha.com/caipu/s-caijiao/', '彩椒'),
 ('https://www.xiangha.com/caipu/s-yuanqiezi/', '圆茄子'),
 ('https://www.xiangha.com/caipu/s-lajiao/', '辣椒'),
 ('https://www.xiangha.com/caipu/s-lvqiezi/', '绿茄子'),
 ('https://www.xiangha.com/caipu/s-sungua/', '笋瓜'),
 ('https://www.xiangha.com/caipu/s-sijidou/', '四季豆'),
 ('https://www.xiangha.com/caipu/s-fanggua/', '方瓜'),
 ('https://www.xiangha.com/caipu/s-jiegua/', '节瓜'),
 ('https://www.xiangha.com/caipu/s-qiukui/', '秋葵'),

 ('https://www.xiangha.com/caipu/s-mogu/', '蘑菇'),
 ('https://www.xiangha.com/caipu/s-caogu/', '草菇'),
 ('https://www.xiangha.com/caipu/s-xianggu/', '香菇'),
 ('https://www.xiangha.com/caipu/s-pinggu/', '平菇'),
 ('https://www.xiangha.com/caipu/s-jinzhengu/', '金针菇'),
 ('https://www.xiangha.com/caipu/s-koumo/', '口蘑'),
 ('https://www.xiangha.com/caipu/s-yiner/', '银耳'),
 ('https://www.xiangha.com/caipu/s-houtougu/', '猴头菇'),
 ('https://www.xiangha.com/caipu/s-zhusun1/', '竹荪'),
 ('https://www.xiangha.com/caipu/s-xingbaogu/', '杏鲍菇'),
 ('https://www.xiangha.com/caipu/s-chashugu/', '茶树菇'),
 ('https://www.xiangha.com/caipu/s-jituigu/', '鸡腿菇'),
 ('https://www.xiangha.com/caipu/s-xieweigu/', '蟹味菇'),
 ('https://www.xiangha.com/caipu/s-niuganjun/', '牛肝菌'),
 ('https://www.xiangha.com/caipu/s-yuanmo/', '元蘑'),
 ('https://www.xiangha.com/caipu/s-muer/', '木耳'),
 ('https://www.xiangha.com/caipu/s-zhenmo/', '榛蘑'),
 ('https://www.xiangha.com/caipu/s-haixiangu/', '海鲜菇'),
 ('https://www.xiangha.com/caipu/s-ganxianggu/', '干香菇'),
 ('https://www.xiangha.com/caipu/s-honggu/', '红菇'),
 ('https://www.xiangha.com/caipu/s-songmo/', '松蘑'),
 ('https://www.xiangha.com/caipu/s-chongcaohua/', '虫草花'),

 ('https://www.xiangha.com/caipu/s-muxu/', '苜蓿'),
 ('https://www.xiangha.com/caipu/s-bawanghua/', '霸王花'),

 ('https://www.xiangha.com/caipu/s-suanmiao/', '蒜苗'),
 ('https://www.xiangha.com/caipu/s-yangcong/', '洋葱'),
 ('https://www.xiangha.com/caipu/s-qingsuan/', '青蒜'),
 ('https://www.xiangha.com/caipu/s-xiaocong/', '小葱'),
 ('https://www.xiangha.com/caipu/s-dacong/', '大葱'),
 ('https://www.xiangha.com/caipu/s-congbai/', '葱白'),
 ('https://www.xiangha.com/caipu/s-dasuan/', '大蒜'),

 ('https://www.xiangha.com/caipu/s-lvdouya/', '绿豆芽'),
 ('https://www.xiangha.com/caipu/s-huangdouya1/', '黄豆芽'),
 ('https://www.xiangha.com/caipu/s-huangdou/', '黄豆'),
 ('https://www.xiangha.com/caipu/s-maodou/', '毛豆'),
 ('https://www.xiangha.com/caipu/s-qingdou/', '青豆'),
 ('https://www.xiangha.com/caipu/s-lvdou/', '绿豆'),
 ('https://www.xiangha.com/caipu/s-heidou/', '黑豆'),
 ('https://www.xiangha.com/caipu/s-candou/', '蚕豆'),
 ('https://www.xiangha.com/caipu/s-yundou/', '芸豆'),
 ('https://www.xiangha.com/caipu/s-hongyaodou/', '红腰豆'),
 ('https://www.xiangha.com/caipu/s-baidou/', '白豆'),
 ('https://www.xiangha.com/caipu/s-chixiaodou/', '赤小豆'),
 ('https://www.xiangha.com/caipu/s-huadou/', '花豆'),
 ('https://www.xiangha.com/caipu/s-wandouli/', '豌豆粒'),
 ('https://www.xiangha.com/caipu/s-baibiandou/', '白扁豆'),
 ('https://www.xiangha.com/caipu/s-xianwandou/', '鲜豌豆'),
 ('https://www.xiangha.com/caipu/s-lingyuzi/', '山药豆'),
 ('https://www.xiangha.com/caipu/s-yingzuidou/', '鹰嘴豆'),

 ('https://www.xiangha.com/caipu/s-doufu/', '豆腐'),
 ('https://www.xiangha.com/caipu/s-doufugan/', '豆腐干'),
 ('https://www.xiangha.com/caipu/s-fuzhu/', '腐竹'),
 ('https://www.xiangha.com/caipu/s-qianzhang/', '千张'),
 ('https://www.xiangha.com/caipu/s-doufusi/', '豆腐丝'),
 ('https://www.xiangha.com/caipu/s-doufupi/', '豆腐皮'),
 ('https://www.xiangha.com/caipu/s-douchi/', '豆豉'),

 ('https://www.xiangha.com/caipu/s-pingguo/', '苹果'),
 ('https://www.xiangha.com/caipu/s-xiangjiao/', '香蕉'),
 ('https://www.xiangha.com/caipu/s-ningmeng/', '柠檬'),
 ('https://www.xiangha.com/caipu/s-boluo/', '菠萝'),
 ('https://www.xiangha.com/caipu/s-caomei/', '草莓'),
 ('https://www.xiangha.com/caipu/s-shancha/', '山楂'),
 ('https://www.xiangha.com/caipu/s-li/', '梨'),
 ('https://www.xiangha.com/caipu/s-lizi1/', '李子'),
 ('https://www.xiangha.com/caipu/s-mihoutao/', '猕猴桃'),
 ('https://www.xiangha.com/caipu/s-youzi/', '柚子'),
 ('https://www.xiangha.com/caipu/s-mangguo/', '芒果'),
 ('https://www.xiangha.com/caipu/s-shizi/', '柿子'),
 ('https://www.xiangha.com/caipu/s-lizhi/', '荔枝'),
 ('https://www.xiangha.com/caipu/s-shiliu/', '石榴'),
 ('https://www.xiangha.com/caipu/s-putao/', '葡萄'),
 ('https://www.xiangha.com/caipu/s-yingtao/', '樱桃'),
 ('https://www.xiangha.com/caipu/s-xigua/', '西瓜'),
 ('https://www.xiangha.com/caipu/s-mugua/', '木瓜'),
 ('https://www.xiangha.com/caipu/s-huolongguo/', '火龙果'),
 ('https://www.xiangha.com/caipu/s-yezi/', '椰子'),
 ('https://www.xiangha.com/caipu/s-wuhuaguo/', '无花果'),
 ('https://www.xiangha.com/caipu/s-guiyuan/', '桂圆'),
 ('https://www.xiangha.com/caipu/s-xiguapi/', '西瓜皮'),
 ('https://www.xiangha.com/caipu/s-sangren/', '桑葚'),
 ('https://www.xiangha.com/caipu/s-tao/', '桃'),
 ('https://www.xiangha.com/caipu/s-manyuemei/', '蔓越莓'),
 ('https://www.xiangha.com/caipu/s-xianggua/', '香瓜'),
 ('https://www.xiangha.com/caipu/s-jinju/', '金桔'),
 ('https://www.xiangha.com/caipu/s-yangmei/', '杨梅'),
 ('https://www.xiangha.com/caipu/s-lanmei/', '蓝莓'),
 ('https://www.xiangha.com/caipu/s-niuyouguo/', '牛油果'),
 ('https://www.xiangha.com/caipu/s-juzi/', '桔子'),
 ('https://www.xiangha.com/caipu/s-yangtao/', '杨桃'),
 ('https://www.xiangha.com/caipu/s-baixiangguo/', '百香果'),
 ('https://www.xiangha.com/caipu/s-hamigua/', '哈密瓜'),
 ('https://www.xiangha.com/caipu/s-liulian/', '榴莲'),
 ('https://www.xiangha.com/caipu/s-ganzhe/', '甘蔗'),
 ('https://www.xiangha.com/caipu/s-foshougan/', '佛手柑'),
 ('https://www.xiangha.com/caipu/s-ganju/', '柑桔'),
 ('https://www.xiangha.com/caipu/s-yingtaofanqie/', '樱桃番茄'),
 ('https://www.xiangha.com/caipu/s-cheng/', '橙'),
 ('https://www.xiangha.com/caipu/s-yali/', '鸭梨'),
 ('https://www.xiangha.com/caipu/s-xuelianguo/', '雪莲果'),
 ('https://www.xiangha.com/caipu/s-fupenzi/', '覆盆子'),
 ('https://www.xiangha.com/caipu/s-heiganlan/', '黑橄榄'),
 ('https://www.xiangha.com/caipu/s-biba/', '枇杷'),
 ('https://www.xiangha.com/caipu/s-putaoyou/', '葡萄柚'),
 ('https://www.xiangha.com/caipu/s-shumei/', '树莓'),
 ('https://www.xiangha.com/caipu/s-xiangli/', '香梨'),
 ('https://www.xiangha.com/caipu/s-chelizi/', '车厘子'),
 ('https://www.xiangha.com/caipu/s-tizi/', '提子'),

 ('https://www.xiangha.com/caipu/s-huasheng/', '花生'),
 ('https://www.xiangha.com/caipu/s-yaoguo/', '腰果'),
 ('https://www.xiangha.com/caipu/s-songzi/', '松子'),
 ('https://www.xiangha.com/caipu/s-hetao/', '核桃'),
 ('https://www.xiangha.com/caipu/s-zhima/', '芝麻'),
 ('https://www.xiangha.com/caipu/s-xingren/', '杏仁'),
 ('https://www.xiangha.com/caipu/s-lianzi/', '莲子'),
 ('https://www.xiangha.com/caipu/s-zhenzi/', '榛子'),
 ('https://www.xiangha.com/caipu/s-xiaweiyiguo/', '夏威夷果'),
 ('https://www.xiangha.com/caipu/s-haidiye/', '海底椰'),
 ('https://www.xiangha.com/caipu/s-zao/', '红枣'),
 ('https://www.xiangha.com/caipu/s-nanguaziren/', '南瓜子'),
 ('https://www.xiangha.com/caipu/s-kaixinguo/', '开心果'),
 ('https://www.xiangha.com/caipu/s-banli/', '板栗'),
 ('https://www.xiangha.com/caipu/s-baiguo/', '白果'),
 ('https://www.xiangha.com/caipu/s-kuihuaziren/', '葵花籽仁'),
 ('https://www.xiangha.com/caipu/s-guiyuanrou/', '桂圆肉'),
 ('https://www.xiangha.com/caipu/s-shanhetao/', '山核桃'),
 ('https://www.xiangha.com/caipu/s-putaogan/', '葡萄干'),
 ('https://www.xiangha.com/caipu/s-yamazi/', '亚麻籽'),
 ('https://www.xiangha.com/caipu/s-heizhima/', '黑芝麻'),
 ('https://www.xiangha.com/caipu/s-mizao/', '蜜枣'),
 ('https://www.xiangha.com/caipu/s-shibing/', '柿饼'),

 ('https://www.xiangha.com/caipu/s-qiaomaimian/', '荞麦面'),
 ('https://www.xiangha.com/caipu/s-mianbao/', '面包'),
 ('https://www.xiangha.com/caipu/s-mifan/', '米饭'),
 ('https://www.xiangha.com/caipu/s-fensi/', '粉丝'),
 ('https://www.xiangha.com/caipu/s-mifen/', '米粉'),
 ('https://www.xiangha.com/caipu/s-quanmaifen/', '全麦粉'),
 ('https://www.xiangha.com/caipu/s-xiaomaimianfen/', '小麦面粉'),
 ('https://www.xiangha.com/caipu/s-yanmaipian/', '燕麦片'),
 ('https://www.xiangha.com/caipu/s-dianfen/', '淀粉'),
 ('https://www.xiangha.com/caipu/s-damizhou/', '大米粥'),

 ('https://www.xiangha.com/caipu/s-maiya/', '麦芽'),
 ('https://www.xiangha.com/caipu/s-dami/', '大米'),
 ('https://www.xiangha.com/caipu/s-nuomi/', '糯米'),
 ('https://www.xiangha.com/caipu/s-heimi/', '黑米'),
 ('https://www.xiangha.com/caipu/s-xiaomi/', '小米'),
 ('https://www.xiangha.com/caipu/s-xiaomai/', '小麦'),
 ('https://www.xiangha.com/caipu/s-yumi/', '玉米'),
 ('https://www.xiangha.com/caipu/s-ximi/', '西米'),
 ('https://www.xiangha.com/caipu/s-yimi/', '薏米'),
 ('https://www.xiangha.com/caipu/s-yanmai/', '燕麦'),
 ('https://www.xiangha.com/caipu/s-hongdou/', '红豆'),
 ('https://www.xiangha.com/caipu/s-zimi/', '紫米'),
 ('https://www.xiangha.com/caipu/s-caomi/', '糙米'),
 ('https://www.xiangha.com/caipu/s-xiangmi/', '香米'),
 ('https://www.xiangha.com/caipu/s-qiaomai/', '荞麦'),
 ('https://www.xiangha.com/caipu/s-gaoliangmi/', '高粱米'),
 ('https://www.xiangha.com/caipu/s-huangmi/', '黄米'),
 ('https://www.xiangha.com/caipu/s-damai/', '大麦'),
 ('https://www.xiangha.com/caipu/s-jingmi/', '粳米'),
 ('https://www.xiangha.com/caipu/s-yaxuenuo/', '鸭血糯'),
 ('https://www.xiangha.com/caipu/s-hongqu/', '红曲'),

 ('https://www.xiangha.com/caipu/s-yanwo/', '燕窝'),
 ('https://www.xiangha.com/caipu/s-renshen/', '人参'),
 ('https://www.xiangha.com/caipu/s-xiangchun/', '香椿'),
 ('https://www.xiangha.com/caipu/s-guihua/', '桂花'),
 ('https://www.xiangha.com/caipu/s-zisu/', '紫苏'),
 ('https://www.xiangha.com/caipu/s-chuanxinlian/', '穿心莲'),
 ('https://www.xiangha.com/caipu/s-luohanguo/', '罗汉果'),
 ('https://www.xiangha.com/caipu/s-jinyinhua/', '金银花'),
 ('https://www.xiangha.com/caipu/s-yuxingcao/', '鱼腥草'),
 ('https://www.xiangha.com/caipu/s-shier/', '石耳'),
 ('https://www.xiangha.com/caipu/s-gouqizi/', '枸杞子'),
 ('https://www.xiangha.com/caipu/s-maidong/', '麦冬'),
 ('https://www.xiangha.com/caipu/s-gegen/', '葛根'),
 ('https://www.xiangha.com/caipu/s-huangchi/', '黄芪'),
 ('https://www.xiangha.com/caipu/s-gouqiye/', '枸杞叶'),
 ('https://www.xiangha.com/caipu/s-juemingzi/', '决明子'),
 ('https://www.xiangha.com/caipu/s-danggui/', '当归'),
 ('https://www.xiangha.com/caipu/s-wumei/', '乌梅'),
 ('https://www.xiangha.com/caipu/s-tianqi/', '田七'),
 ('https://www.xiangha.com/caipu/s-qianshimi/', '芡实'),
 ('https://www.xiangha.com/caipu/s-zisuye/', '紫苏叶'),
 ('https://www.xiangha.com/caipu/s-jinyingzi/', '金樱子'),
 ('https://www.xiangha.com/caipu/s-gancao/', '甘草'),
 ('https://www.xiangha.com/caipu/s-guipi/', '桂皮'),
 ('https://www.xiangha.com/caipu/s-bohe/', '薄荷'),
 ('https://www.xiangha.com/caipu/s-shashen/', '沙参'),
 ('https://www.xiangha.com/caipu/s-heye/', '荷叶'),
 ('https://www.xiangha.com/caipu/s-xiyangshen/', '西洋参'),
 ('https://www.xiangha.com/caipu/s-rougui/', '肉桂'),
 ('https://www.xiangha.com/caipu/s-chenpi/', '陈皮'),
 ('https://www.xiangha.com/caipu/s-fulian/', '茯苓'),
 ('https://www.xiangha.com/caipu/s-baizhi/', '白芷'),
 ('https://www.xiangha.com/caipu/s-lingzhi/', '灵芝'),
 ('https://www.xiangha.com/caipu/s-yuzhu/', '玉竹'),
 ('https://www.xiangha.com/caipu/s-ganhuanghuacai/', '干黄花菜'),
 ('https://www.xiangha.com/caipu/s-sheergen/', '折耳根'),
 ('https://www.xiangha.com/caipu/s-jupi/', '桔皮'),
 ('https://www.xiangha.com/caipu/s-dingxiang/', '丁香'),
 ('https://www.xiangha.com/caipu/s-wuzhimaotao/', '五指毛桃'),
 ('https://www.xiangha.com/caipu/s-dangshen/', '党参'),
 ('https://www.xiangha.com/caipu/s-lanxiangzi/', '兰香子'),
 ('https://www.xiangha.com/caipu/s-dongchongxiacao/', '冬虫夏草'),
 ('https://www.xiangha.com/caipu/s-ejiaofen/', '阿胶粉'),
 ('https://www.xiangha.com/caipu/s-tusanqi/', '土三七'),
 ('https://www.xiangha.com/caipu/s-dahuang/', '大黄'),
 ('https://www.xiangha.com/caipu/s-tianma/', '天麻'),
 ('https://www.xiangha.com/caipu/s-chengpi/', '橙皮'),
 ('https://www.xiangha.com/caipu/s-baidoukou/', '白豆蔻'),
 ('https://www.xiangha.com/caipu/s-shihu/', '石斛'),
 ('https://www.xiangha.com/caipu/s-sharen/', '砂仁'),
 ('https://www.xiangha.com/caipu/s-honghua/', '红花'),
 ('https://www.xiangha.com/caipu/s-roukou/', '肉蔻'),
 ('https://www.xiangha.com/caipu/s-aiye/', '艾叶'),
 ('https://www.xiangha.com/caipu/s-caoguo/', '草果'),
 ('https://www.xiangha.com/caipu/s-xunyicao/', '薰衣草'),
 ('https://www.xiangha.com/caipu/s-canghonghua/', '藏红花'),
 ('https://www.xiangha.com/caipu/s-doukou/', '豆蔻'),
 ('https://www.xiangha.com/caipu/s-yesuan/', '野蒜'),
 ('https://www.xiangha.com/caipu/s-yujiaofen/', '鱼胶粉'),
 ('https://www.xiangha.com/caipu/s-yuxingcaoye/', '鱼腥草叶'),
 ('https://www.xiangha.com/caipu/s-yuxingcaogen/', '鱼腥草根'),
 ('https://www.xiangha.com/caipu/s-shuweicao/', '鼠尾草'),
 ('https://www.xiangha.com/caipu/s-ejiao/', '阿胶'),
 ('https://www.xiangha.com/caipu/s-danbaifen/', '蛋白粉'),
 ('https://www.xiangha.com/caipu/s-youzipi/', '柚子皮'),
 ('https://www.xiangha.com/caipu/s-xuanshen/', '玄参'),
 ('https://www.xiangha.com/caipu/s-ganjiang/', '干姜'),
 ('https://www.xiangha.com/caipu/s-chuanbei/', '川贝'),
 ('https://www.xiangha.com/caipu/s-pugongying/', '蒲公英'),
 ('https://www.xiangha.com/caipu/s-xuelianhua/', '雪莲花'),
 ('https://www.xiangha.com/caipu/s-taojiao/', '桃胶'),
 ('https://www.xiangha.com/caipu/s-hupo/', '琥珀'),
 ('https://www.xiangha.com/caipu/s-tufuling/', '土茯苓'),
 ('https://www.xiangha.com/caipu/s-meiguiqie/', '玫瑰茄'),
 ('https://www.xiangha.com/caipu/s-wubeizi/', '五倍子'),
 ('https://www.xiangha.com/caipu/s-jingjie/', '荆芥'),
 ('https://www.xiangha.com/caipu/s-midiexiang/', '迷迭香'),
 ('https://www.xiangha.com/caipu/s-niubangzi/', '牛蒡子'),
 ('https://www.xiangha.com/caipu/s-zicao/', '紫草'),
 ('https://www.xiangha.com/caipu/s-beiqi/', '北芪'),
 ('https://www.xiangha.com/caipu/s-daqingye/', '大青叶'),
 ('https://www.xiangha.com/caipu/s-tianhuafen/', '天花粉'),
 ('https://www.xiangha.com/caipu/s-shegan/', '射干'),
 ('https://www.xiangha.com/caipu/s-baishen/', '白参'),
 ('https://www.xiangha.com/caipu/s-ruxiang/', '乳香'),
 ('https://www.xiangha.com/caipu/s-jiangchan/', '僵蚕'),
 ('https://www.xiangha.com/caipu/s-quanxie/', '全蝎'),
 ('https://www.xiangha.com/caipu/s-taohua/', '桃花'),
 ('https://www.xiangha.com/caipu/s-jianghuang/', '姜黄'),

 ('https://www.xiangha.com/caipu/s-weijing/', '味精'),
 ('https://www.xiangha.com/caipu/s-hongtang/', '红糖'),
 ('https://www.xiangha.com/caipu/s-bingtang/', '冰糖'),
 ('https://www.xiangha.com/caipu/s-baitang/', '白糖'),
 ('https://www.xiangha.com/caipu/s-jiang/', '姜'),
 ('https://www.xiangha.com/caipu/s-cu/', '醋'),
 ('https://www.xiangha.com/caipu/s-doubanjiang/', '豆瓣酱'),
 ('https://www.xiangha.com/caipu/s-fanqiejiang/', '番茄酱'),
 ('https://www.xiangha.com/caipu/s-shankui/', '山葵'),
 ('https://www.xiangha.com/caipu/s-lagen/', '辣根'),
 ('https://www.xiangha.com/caipu/s-ganlajiao/', '干辣椒'),
 ('https://www.xiangha.com/caipu/s-hujiao/', '胡椒'),
 ('https://www.xiangha.com/caipu/s-jiemo/', '芥末'),
 ('https://www.xiangha.com/caipu/s-kali/', '咖喱'),
 ('https://www.xiangha.com/caipu/s-zhimayou/', '芝麻油'),
 ('https://www.xiangha.com/caipu/s-hujiaofen/', '胡椒粉'),
 ('https://www.xiangha.com/caipu/s-huajiao/', '花椒'),
 ('https://www.xiangha.com/caipu/s-jiangyou/', '酱油'),
 ('https://www.xiangha.com/caipu/s-huixiangzi/', '茴香籽'),
 ('https://www.xiangha.com/caipu/s-bajiao/', '八角'),
 ('https://www.xiangha.com/caipu/s-zhuyou/', '猪油'),
 ('https://www.xiangha.com/caipu/s-huashengyou/', '花生油'),
 ('https://www.xiangha.com/caipu/s-sudafen/', '苏打粉'),
 ('https://www.xiangha.com/caipu/s-liaojiu/', '料酒'),
 ('https://www.xiangha.com/caipu/s-haoyou/', '蚝油'),
 ('https://www.xiangha.com/caipu/s-ziran/', '孜然'),

 ('https://www.xiangha.com/caipu/s-qiaokeli/', '巧克力'),
 ('https://www.xiangha.com/caipu/s-jinqiangyuguantou/', '金枪鱼罐头'),
 ('https://www.xiangha.com/caipu/s-hongdousha/', '红豆沙'),
 ('https://www.xiangha.com/caipu/s-maiyatang/', '麦芽糖'),
 ('https://www.xiangha.com/caipu/s-baomihua/', '爆米花'),

 ('https://www.xiangha.com/caipu/s-niunai/', '牛奶'),
 ('https://www.xiangha.com/caipu/s-suannai/', '酸奶'),
 ('https://www.xiangha.com/caipu/s-doujiang/', '豆浆'),
 ('https://www.xiangha.com/caipu/s-fengmi/', '蜂蜜'),
 ('https://www.xiangha.com/caipu/s-lvcha/', '绿茶'),
 ('https://www.xiangha.com/caipu/s-kekefen/', '可可粉'),
 ('https://www.xiangha.com/caipu/s-oufen/', '藕粉'),
 ('https://www.xiangha.com/caipu/s-jiangmijiu/', '江米酒'),
 ('https://www.xiangha.com/caipu/s-chaye/', '茶叶'),
 ('https://www.xiangha.com/caipu/s-huangjiu/', '黄酒'),
 ('https://www.xiangha.com/caipu/s-huacha/', '花茶'),
 ('https://www.xiangha.com/caipu/s-puercha/', '普洱茶'),
 ('https://www.xiangha.com/caipu/s-ningmengshui/', '柠檬水'),
 ('https://www.xiangha.com/caipu/s-meiguihuacha/', '玫瑰花茶'),
 ('https://www.xiangha.com/caipu/s-hongcha/', '红茶'),
 ('https://www.xiangha.com/caipu/s-huafen/', '花粉'),
 ('https://www.xiangha.com/caipu/s-juhuacha/', '菊花茶'),
 ('https://www.xiangha.com/caipu/s-tieguanyin/', '铁观音'),
 ('https://www.xiangha.com/caipu/s-damaicha/', '大麦茶'),
 ('https://www.xiangha.com/caipu/s-youzicha/', '柚子茶'),
 ('https://www.xiangha.com/caipu/s-pingguocu/', '苹果醋'),
 ('https://www.xiangha.com/caipu/s-ningmengcha/', '柠檬茶'),
 ('https://www.xiangha.com/caipu/s-sangshenjiu/', '桑葚酒'),
 ('https://www.xiangha.com/caipu/s-longjingcha/', '龙井茶')]
# Crawl responsibly by identifying yourself (and your website) on the user-agent
# USER_AGENT = "FoodsSpider (+http://www.yourdomain.com)"



# Configure maximum concurrent requests performed by Scrapy (default: 16)
# CONCURRENT_REQUESTS = 32

# Configure a delay for requests for the same website (default: 0)
# See https://docs.scrapy.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
DOWNLOAD_DELAY = 1
# The download delay setting will honor only one of:
# CONCURRENT_REQUESTS_PER_DOMAIN = 16
# CONCURRENT_REQUESTS_PER_IP = 16

# Disable cookies (enabled by default)
# COOKIES_ENABLED = False

# Disable Telnet Console (enabled by default)
# TELNETCONSOLE_ENABLED = False

# Override the default request headers:
DEFAULT_REQUEST_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en",
    'user-agent:': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/103.0.5060.134',

}

# Enable or disable spider middlewares
# See https://docs.scrapy.org/en/latest/topics/spider-middleware.html
# SPIDER_MIDDLEWARES = {
#    "FoodsSpider.middlewares.FoodsSpiderSpiderMiddleware": 543,
# }

# Enable or disable downloader middlewares
# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
# DOWNLOADER_MIDDLEWARES = {
#    "FoodsSpider.middlewares.FoodsSpiderDownloaderMiddleware": 543,
# }

# Enable or disable extensions
# See https://docs.scrapy.org/en/latest/topics/extensions.html
# EXTENSIONS = {
#    "scrapy.extensions.telnet.TelnetConsole": None,
# }

# Configure item pipelines
# See https://docs.scrapy.org/en/latest/topics/item-pipeline.html
# ITEM_PIPELINES = {
#    "FoodsSpider.pipelines.FoodsSpiderPipeline": 300,
# }

# Enable and configure the AutoThrottle extension (disabled by default)
# See https://docs.scrapy.org/en/latest/topics/autothrottle.html
# AUTOTHROTTLE_ENABLED = True
# The initial download delay
# AUTOTHROTTLE_START_DELAY = 5
# The maximum download delay to be set in case of high latencies
# AUTOTHROTTLE_MAX_DELAY = 60
# The average number of requests Scrapy should be sending in parallel to
# each remote server
# AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
# Enable showing throttling stats for every response received:
# AUTOTHROTTLE_DEBUG = False

# Enable and configure HTTP caching (disabled by default)
# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings
# HTTPCACHE_ENABLED = True
# HTTPCACHE_EXPIRATION_SECS = 0
# HTTPCACHE_DIR = "httpcache"
# HTTPCACHE_IGNORE_HTTP_CODES = []
# HTTPCACHE_STORAGE = "scrapy.extensions.httpcache.FilesystemCacheStorage"

# Set settings whose default value is deprecated to a future-proof value
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"
